version: '3'
services:
  nginx:
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container(Nginx)
  node-app:
    build:
        context: . # Build the Dockerfile in the current directory
        args:
          - NODE_ENV=production
    environment:
      - NODE_ENV=production # Set environment variable NODE_ENV to production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js # Override the default command to run the production server
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  