version: '3'
services:
  nginx:
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container(Nginx)
  node-app:
    platform: linux/amd64
    deploy: # Deployment configuration for the Node.js application using Docker Swarm
      replicas: 8 # Run 8 replicas of the Node.js application
      restart_policy:
        condition: any # Restart the container on any failure
      update_config:
        parallelism: 2 # Update 2 containers at a time during rolling updates
        delay: 10s # Wait for 10 seconds between updates
    build:
        context: . # Build the Dockerfile in the current directory
        args:
          - NODE_ENV=production
    environment:
      - NODE_ENV=production # Set environment variable NODE_ENV to production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js # Override the default command to run the production server
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  